using Serilog;
using FluentValidation;
using StoreApp.Services;
using StoreApp.Security;
using StoreApp.Validators;
using StoreApp.Extensions;
using StoreApp.Data;
using Microsoft.OpenApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.RateLimiting;
using System.Threading.RateLimiting;
using System.Text;
using DotNetEnv;

Env.Load();
var builder = WebApplication.CreateBuilder(args);

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Information()
    .WriteTo.Console()
    .WriteTo.File(
        "logs/storeapp-.log",
        rollingInterval: RollingInterval.Day,
        retainedFileCountLimit: 30,
        shared: true,
        flushToDiskInterval: TimeSpan.FromSeconds(1)
    )
    .CreateLogger();

builder.Host.UseSerilog();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddScoped<ProductService>();
builder.Services.AddScoped<CategoryService>();
builder.Services.AddSingleton<PasswordService>();
builder.Services.AddSingleton<TokenService>();
builder.Services.AddScoped<AuthService>();
builder.Services.AddScoped<UserService>();
builder.Services.AddSingleton<HtmlSanitizerService>();

builder.Services.AddControllers();

var connectionString =
    $"Host={Environment.GetEnvironmentVariable("DB_HOST")};" +
    $"Port={Environment.GetEnvironmentVariable("DB_PORT")};" +
    $"Database={Environment.GetEnvironmentVariable("DB_NAME")};" +
    $"Username={Environment.GetEnvironmentVariable("DB_USER")};" +
    $"Password={Environment.GetEnvironmentVariable("DB_PASSWORD")};" +
    $"SSL Mode=Require;Trust Server Certificate=true";

builder.Services.AddDbContext<StoreAppDbContext>(
    options =>
        options.UseNpgsql(
            connectionString
            // builder.Configuration.GetConnectionString(
            //     "DefaultConnection")
            
            ));

builder.Services.AddAuthentication(
    JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
    options.TokenValidationParameters =
        new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,

            ClockSkew = TimeSpan.Zero,

            ValidIssuer = Environment.GetEnvironmentVariable("JWT_ISSUER"),

            ValidAudience = Environment.GetEnvironmentVariable("JWT_AUDIENCE"),

            IssuerSigningKey =
                new SymmetricSecurityKey(
                    Encoding.UTF8.GetBytes(
                        Environment.GetEnvironmentVariable("JWT_SECRET_KEY")!))
        };

    options.Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = context =>
        {
            Log.Warning(context.Exception, "JWT Authentication Failed");

            return Task.CompletedTask;
        },

        OnTokenValidated = context =>
        {
            Log.Information("User authenticated successfully");

            return Task.CompletedTask;
        }
    };
});

builder.Services.AddAuthorization();

builder.Services.AddValidatorsFromAssemblyContaining<ProductValidator>();

builder.Services.AddRateLimiter(options =>
{
    options.AddFixedWindowLimiter(
        "ApiPolicy",
        config =>
        {
            config.PermitLimit = 100;
            config.Window = TimeSpan.FromMinutes(1);
        });
});

builder.Services.AddSwaggerGen(options =>
            {
                // Configure basic information for the OpenAPI documentation (optional)
                options.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "StoreApp API",
                    Version = "v1",
                    Description = "ASP.NET Core Web API with JWT authentication. " +
                    "Target Framework is .NET 10. " +
                    "Swashbuckle.AspNetCore 10.1.7 is used."
                });

                // Add a Security Scheme (using a JWT Bearer token).
                options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    Name = "Authorization",
                    Type = SecuritySchemeType.Http,
                    Scheme = "bearer",
                    BearerFormat = "JWT",
                    In = ParameterLocation.Header,
                    Description = "Please enter token"
                });

                // Add a Security Requirement (without this, even if you set 
                // the JWT in the Authorize window, Swagger will not include
                // Authorization: Bearer ... in the request header).
                // In the code below, `document` is the OpenAPI document 
                // generated by SwaggerGen. Add a Security Requirement to 
                // that document.

                options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });

});

var app = builder.Build();

// app.UseHttpsRedirection();

// if (!app.Environment.IsDevelopment())
// {
    // app.UseHsts();
// }

app.UseRateLimiter();

app.UseGlobalExceptionHandler();

app.UseSecurityHeaders();

app.UseSerilogRequestLogging();

// if (app.Environment.IsDevelopment())
// {
app.UseSwagger();
app.UseSwaggerUI();
// }

app.UseAuthentication();

app.UseAuthorization();

app.MapControllers();

app.MapGet("/", () => "Hello World!").ExcludeFromDescription();

app.Run();