GET http://localhost:5010

###

GET http://localhost:5010/api/products

###

POST http://localhost:5010/api/products
Content-Type: application/json

{
  "name": "Samo Fashion",
  "price": 140,
  "hasDiscount": true,
  "productType": "clothing",
  "categoryId": 1,
  "size": 5
}

###

PUT http://localhost:5010/api/products/3
Content-Type: application/json

{
  "id": 3,
  "name": "Samo Custom 2 piece",
  "hasDiscount": true,
  "categoryId": 1,
  "category": {
    "id": 1,
    "name": "Clothing"
  },
  "price": 120
}

###

DELETE http://localhost:5010/api/products/3

###

GET http://localhost:5010/api/categories/1

###

POST http://localhost:5010/api/categories
Content-Type: application/json

{
  "name": "Cosmetics"
}

###

POST http://localhost:5010/api/products
Content-Type: application/json

{
  "name": "iPhone 15",
  "price": 1500,
  "hasDiscount": true,
  "productType": "electronics",
  "categoryId": 2,
  "warranty": true,
  "brand": "Apple"
}